### PR TITLE
ci: update for Go 1.8

### PR DESCRIPTION
**Pull request by nathany**
two most recent stable versions + tip

### CODE REVIEW

**Comment by nathany** [comment]
it looks like there is a data race to fix

**Comment by bep** [comment]
>it looks like there is a data race to fix

https://github.com/fsnotify/fsnotify/issues/150

**Comment by nathany** [comment]
Still seeing data races on Travis. Doh!

**Comment by pattyshack** [comment]
the data race is in the bsd build; that uses kqueue instead of inotify.  #177 will not help here

**Comment by nathany** [comment]
data races in all the places

will come back to that one. 💤

**Comment by nathany** [comment]
on macOS Sierra 10.12

```
❯ go test -race -test.count=10
PASS
ok  	github.com/fsnotify/fsnotify	104.165s

fsnotify git/master  
❯ go16 test -race -test.count=10
``

... the later doesn't seem to be finishing anytime soon

**Comment by nathany** [comment]
well this is embarrassing... 😊 

updated for Go 1.8

**Comment by nathany** [comment]
also request Go 1.8 for AppVeyor. https://github.com/appveyor/ci/issues/1330

Currently Windows tests are using Go 1.7.1

**Comment by twpayne** [comment]
FWIW you can use `1.x` to get the latest stable release of Go, and (for example) `1.7.x` to get the latest version of 1.7. For example:

```yaml
go:
  - 1.7.x
  - 1.x
  - tip
```

**Comment by nathany** [comment]
@twpayne Thanks for the note. The only problem with using `.x` is we need to wait for Travis CI to update their aliases, but they are in place now. I will update.

See: https://github.com/travis-ci/travis-build/pull/956

**Pull request merged**
