### PR TITLE
kqueue: wait without timeout

### PR DESCRIPTION
**Pull request by fjl**
As noted in #24, reading from the kqueue won't unblock when
it is closed on all platforms. This commit solves the issue by
additionally watching on a pipe which is closed when Watcher
is closed. This makes the read timeout unnecessary.

### CODE REVIEW

**Comment by fjl** [comment]
I cannot reproduce the failure on Travis and it seems unrelated to the PR.

**Comment by fjl** [comment]
The tests pass on FreeBSD, too.

**Comment by nathany** [comment]
I'll re-run Travis to see if it's being flaky.

**Comment by fjl** [comment]
Looks like it worked this time

**Comment by fjl** [comment]
I found a minor issue with how the pipe is set up and fixed it. Travis still passing.

**Comment by fjl** [comment]
Any ETA on getting this merged?

**Comment by nathany** [comment]
Sorry, still haven't reviewed it yet.

**Comment by pquerna** [comment]
I was also seeing Close() hangs as described in #89 -- at $job we are now carrying this patch on our vendor'ed copy of fsnotify, would love to see it merged.

**Comment by nathany** [comment]
I'm not that familiar with `syscall.Pipe`. Hoping someone will review this.

**Comment by fjl** [comment]
rebased

**Comment by fjl** [comment]
Is there anything I can do to get this merged?

**Comment by nathany** [comment]
There is currently a data race issue with kqueue on master, which should be remedied first.
https://github.com/fsnotify/fsnotify/pull/162#issuecomment-251575890

As to this PR, we need some familiar with epoll to do the code review.

**Comment by arp242** [comment]
A lot of things changed since this PR was opened and it doesn't rebase cleanly with quite a few conflicts. It's not entirely clear to me if this problem has been solved since 2014 or if it still exists.

Either way, I think it would be good to have a test case; I ran `go test -race -count=100` on FreeBSD (13) and that runs without problems, but maybe it only happens on macOS?

**Comment by nathany** [comment]
@arp242 GitHub Actions will run on macOS, if there is a useful test case, but not sure about running such a high count.

On macOS 12.4:

> ❯ go test -race -count=100
> panic: test timed out after 10m0s

**Comment by arp242** [comment]
Oh, you'll have to add `-timeout=20m` or some such; the timeout applies to the entire test run, not a single test, so if that takes too long it will time out.

> GitHub Actions will run on macOS, if there is a useful test case, but not sure about running such a high count.

Yeah, just a quick low-effort way to see if intermittent problems show up; if they do, a dedicated (non-slow) test case can be added.

**Comment by nathany** [comment]
This is the result running another time on macOS 12.5:

```
❯ go test -race -count=100 -timeout=20m
--- FAIL: TestFsnotifyDeleteWatchedDir (0.52s)
    integration_test.go:460: error received: fdopendir /var/folders/82/9wkthct972xb6h3nwsx2rfnh0000gn/T/fsnotify1522497754: no such file or directory
    integration_test.go:471: event received: "/var/folders/82/9wkthct972xb6h3nwsx2rfnh0000gn/T/fsnotify1522497754/TestFsnotifyEventsExisting.testfile": REMOVE
    integration_test.go:471: event received: "/var/folders/82/9wkthct972xb6h3nwsx2rfnh0000gn/T/fsnotify1522497754": REMOVE
FAIL
exit status 1
FAIL	github.com/fsnotify/fsnotify	886.645s
```

**Comment by arp242** [comment]
Coolio, I can't reproduce that on FreeBSD (just tried again to be sure), but it confirms that the problem still exists, and that it's specific to macOS and not all of kqueue (*probably*).

So need to rebase and write a decent test case which doesn't take 15 minutes, probably something [similar to this](https://github.com/fsnotify/fsnotify/pull/465/files#diff-ed1088fda4ca38792b99302b355705eb525017fca294e83858422bb430d8cc59R1247).

**Comment by arp242** [comment]
#262 seems to do the same btw, might want to go with that one as it seems a bit simpler.

**Comment by arp242** [comment]
New version of this PR: #480

I couldn't update this PR for some reason; I guess the branch/fork disappeared after all these years? Anyway, it's essentially the same patch, but rebased on the latest main and with some minor cleanups.

**Pull request closed without merging**
