### PR TITLE
Adding test for failure in kqueue close

### PR DESCRIPTION
**Pull request by nikunjy**
Run the test on a mac 
`go test -run TestWatcherClose -count 5`

### CODE REVIEW

**Comment by nathany** [comment]
Sorry, we need to figure out why these tests are failing.

**Comment by nathany** [comment]
Thanks for providing a failing test. I won't be merging it until we have a fix, nor will I be merging in with an additional testing dependency (as good as testify may be).

**Comment by nikunjy** [comment]
@nathany fair enough. I slacked off on making the fix. Will bounce back with the fix and do the test without testify.

**Comment by nathany** [comment]
Thanks. Would you mind also taking a peek at #124?

**Pull request closed without merging**
