### PR TITLE
Also create epoll and pipe fds with close-on-exec (#155)

### PR DESCRIPTION
**Pull request by JohannesEbke**
* Add the unix.O_CLOEXEC to the Pipe2 call
* Add unix.EPOLL_CLOEXEC to the Epoll call

I've signed the CLA.

#### What does this pull request do?
When creating a fsnotify.NewWatcher(), four file descriptors are opened: One for inotify, one for epoll and two for the two ends of a pipe. Only the inotify one has CLOEXEC set. This PR adds the CLOEXEC flag to all four file descriptors, preventing a leak in cases where execve is used e.g. to reload an executable on code change.

#### Where should the reviewer start?
I read the manpages of pipe2 and epoll_create2 to get an idea of the flags.

#### How should this be manually tested?
In a simple program which just opens a NewWatcher, does a syscall.Exec, and sleeps, the difference in the number of open file descriptors is visible in /proc/<pid>/fd/

### CODE REVIEW

**Comment by pwaller** [comment]
I can confirm that this fixes a problem I see, too. Bit surprised this wasn't fixed in #178.

**Comment by sipsma** [comment]
Is there anything preventing this fix from being merged (other than needing a re-base on master)? This PR is from 2017 but the issue of these FDs leaking across execs is still present today.

**Comment by JohannesEbke** [comment]
I've rebased the patch onto current master, everything still seems to work fine. It would be good to have it merged.

**Comment by cpuguy83** [comment]
I just force-pushed a no-op change to try and re-trigger the CI.

**Comment by cpuguy83** [comment]
ugh 😞 CI issues due to golint not working on go1.8 anymore.
Also appveyor/branch is not doing anything need to look into that as well. Can't merge until these are cleared up.

**Comment by cpuguy83** [comment]
Finally, all green. Merging. Thanks! 🎉 ❤️

**Comment by pwaller** [comment]
:tada:

**Pull request merged**
