### PR TITLE
Run cross-compilation builds on every push

### PR DESCRIPTION
**Pull request by nshalman**
#### What does this pull request do?

This creates a Github action to run cross-compilation
builds for all supported targets (or at least that's the idea)

This would have caught #389 and should
catch build failures for supported targets.

#### Where should the reviewer start?

The output of the builds

#### How should this be manually tested?
N/A

### CODE REVIEW

**Comment by nshalman** [comment]
Builds ran in my fork: https://github.com/nshalman/fsnotify/actions/runs/1709688309

**Comment by nshalman** [comment]
Even on my illumos system I could have caught that:
```
~/fsnotify $ git checkout v1.5.0 ; GOOS=freebsd GOARCH=amd64 go build
Note: switching to 'v1.5.0'.
<snip>
HEAD is now at 08848a0 v1.5.0 preparation (#380)
# github.com/fsnotify/fsnotify
./kqueue.go:193:43: undefined: unix.O_SYMLINK
```

**Comment by nshalman** [comment]
I think this PR is a good example of how I intend to maintain quality in this project across all supported platforms. I hope you agree, @nathany.

**Review by nathany — APPROVED** [review]
very good idea :shipit:

**Pull request merged**
